In [49]:
import numpy as np


In [191]:
class ts_concatted:
    def __init__(self, array:np.ndarray, lengths:np.ndarray,  lags:np.ndarray):
        """
        array should be concatted arrays,
        lengths should be the lengths of the individual arrays,
        lags should be the lags to be used,
        """
        assert len(lags) > 1, "Come on dude this is a time series, you gotta be a bit serious !!!!"
        assert len(array) == sum(lengths), "For partition, sum of the lengths should be equal to total size of the time series concattenated"
        ## -- ##
        self.array = array
        self.lengths = np.cumsum(lengths)
        self.lags = lags
        self.horizons = [len_ - lag+1 for len_, lag in zip(lengths, lags)]
        self.cumhors = np.cumsum(self.horizons)
        self.m = {i:j-i for i,j in enumerate(np.cumsum([0]+lags[:-1]))}

    def __place__(self, x:int, array:np.ndarray)->int:
        N = len(array, )                      
        if 0 <= x < array[0]:
            return 0
        for i in range(N-1):
            if  array[i] <= x < array[i+1]:
                return i+1
    
    def __getitem__(self, i):
        if i > self.__len__() -1:
            raise IndexError
        ### Otherwise go ahead my son ### 
        place_ = self.__place__(i, self.cumhors)
        
        X = self.array[i+self.m[place_]:i+self.m[place_]+self.lags[place_]]
        enum = place_
        return X[:-1], X[-1], enum
 
    def __len__(self)->int:
        return len(self.array) - sum(self.lags)+len(self.lags)

In [193]:
import numpy as np
a = [(-1)**i for i in range(15)]
b = [(-2)**(i+1) for i in range(10)]
c = [1 for i in range(6)]
n = [i for i in range(15)]

L = [15, 10, 6, 15]

lags = [4, 4, 3, 5]
lags_ = [u-v+1 for u,v in zip(L,lags)]
t = {i:j-i for i,j in enumerate(np.cumsum([0]+lags[:-1]))}
m = np.concatenate([a,b,c,n], axis = 0)


In [194]:
ts = ts_concatted(m, L, lags)

In [195]:
for m in ts:
    print(m)


(array([ 1, -1,  1]), -1, 0)
(array([-1,  1, -1]), 1, 0)
(array([ 1, -1,  1]), -1, 0)
(array([-1,  1, -1]), 1, 0)
(array([ 1, -1,  1]), -1, 0)
(array([-1,  1, -1]), 1, 0)
(array([ 1, -1,  1]), -1, 0)
(array([-1,  1, -1]), 1, 0)
(array([ 1, -1,  1]), -1, 0)
(array([-1,  1, -1]), 1, 0)
(array([ 1, -1,  1]), -1, 0)
(array([-1,  1, -1]), 1, 0)
(array([-2,  4, -8]), 16, 1)
(array([ 4, -8, 16]), -32, 1)
(array([ -8,  16, -32]), 64, 1)
(array([ 16, -32,  64]), -128, 1)
(array([ -32,   64, -128]), 256, 1)
(array([  64, -128,  256]), -512, 1)
(array([-128,  256, -512]), 1024, 1)
(array([1, 1]), 1, 2)
(array([1, 1]), 1, 2)
(array([1, 1]), 1, 2)
(array([1, 1]), 1, 2)
(array([0, 1, 2, 3]), 4, 3)
(array([1, 2, 3, 4]), 5, 3)
(array([2, 3, 4, 5]), 6, 3)
(array([3, 4, 5, 6]), 7, 3)
(array([4, 5, 6, 7]), 8, 3)
(array([5, 6, 7, 8]), 9, 3)
(array([6, 7, 8, 9]), 10, 3)
(array([ 7,  8,  9, 10]), 11, 3)
(array([ 8,  9, 10, 11]), 12, 3)
(array([ 9, 10, 11, 12]), 13, 3)
(array([10, 11, 12, 13]), 14, 3)


In [5]:
def ind(i):
    place_ = place(i, np.cumsum(lags_))
    return i+t[place_], place_, m[i+t[place_]:i+t[place_]+lags[place_] ]

In [83]:
for i in range(1000):
    print(ind(i),i)


(0, 0, array([ 1, -1,  1, -1])) 0
(1, 0, array([-1,  1, -1,  1])) 1
(2, 0, array([ 1, -1,  1, -1])) 2
(3, 0, array([-1,  1, -1,  1])) 3
(4, 0, array([ 1, -1,  1, -1])) 4
(5, 0, array([-1,  1, -1,  1])) 5
(6, 0, array([ 1, -1,  1, -1])) 6
(7, 0, array([-1,  1, -1,  1])) 7
(8, 0, array([ 1, -1,  1, -1])) 8
(9, 0, array([-1,  1, -1,  1])) 9
(10, 0, array([ 1, -1,  1, -1])) 10
(11, 0, array([-1,  1, -1,  1])) 11
(15, 1, array([-2,  4, -8, 16])) 12
(16, 1, array([  4,  -8,  16, -32])) 13
(17, 1, array([ -8,  16, -32,  64])) 14
(18, 1, array([  16,  -32,   64, -128])) 15
(19, 1, array([ -32,   64, -128,  256])) 16
(20, 1, array([  64, -128,  256, -512])) 17
(21, 1, array([-128,  256, -512, 1024])) 18
(25, 2, array([1, 1, 1])) 19
(26, 2, array([1, 1, 1])) 20
(27, 2, array([1, 1, 1])) 21
(28, 2, array([1, 1, 1])) 22
(31, 3, array([5, 5, 5, 5, 5])) 23
(32, 3, array([5, 5, 5, 5, 5])) 24
(33, 3, array([5, 5, 5, 5, 5])) 25
(34, 3, array([5, 5, 5, 5, 5])) 26
(35, 3, array([5, 5, 5, 5, 5])) 27
(36, 

KeyError: None