In [58]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [175]:
x = torch.randn(10, 128, 512)

In [179]:
Q = torch.randn(128, 128)/(128)**0.5
W = torch.randn(128, 128)/(128)**0.5
E = torch.randn(128, 128)/(128)**0.5
## the above guys are attention guys

In [180]:
x_q = (Q @ x)
x_w = (W @ x)
x_e = (E @ x)

In [181]:
x_q.shape

torch.Size([10, 128, 512])

In [182]:
x_q = x_q.view(-1, 4, 32, 512)
x_w = x_w.view(-1, 4, 32, 512)
x_e = x_e.view(-1, 4, 32, 512)

In [211]:
(x_e @ nn.Softmax(-2)((x_q.transpose(-2, -1) @ x_w))).view(-1, 128, 512)

tensor([[[-2.6703e-01, -3.0387e-01,  4.5823e-01,  ...,  2.3021e-01,
           3.5491e-01, -1.1374e-01],
         [-3.8753e-01,  6.9835e-01, -7.1523e-02,  ...,  1.1040e+00,
           6.4085e-02, -1.2891e-01],
         [-6.5734e-01, -2.2533e-01,  1.2000e+00,  ...,  1.0811e+00,
           6.0986e-01, -3.6201e-01],
         ...,
         [ 1.2474e+00,  3.0609e-01,  8.7478e-01,  ..., -2.6188e-02,
           7.0965e-01,  3.9301e-01],
         [ 1.5619e-01,  6.9694e-01,  5.4939e-01,  ...,  3.3038e-01,
          -3.4769e-01, -5.7895e-01],
         [-1.3458e-01, -4.3366e-01, -8.0597e-02,  ..., -1.2417e-01,
          -9.9422e-01,  2.5048e-01]],

        [[-1.6127e+00,  4.3400e-01,  8.9820e-01,  ...,  1.3726e+00,
          -8.1442e-01, -6.6873e-01],
         [ 8.4259e-01, -6.8422e-01,  7.3308e-01,  ...,  5.7165e-01,
           4.1729e-01,  4.2767e-01],
         [ 2.6765e-02, -1.0417e+00,  4.0865e-01,  ..., -5.2435e-02,
           4.2385e-01,  6.3520e-01],
         ...,
         [-4.7784e-02,  5

In [163]:
x = torch.tensor([i for i in range(64)])
x = x.view(4, 4,4)

In [164]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]])

In [165]:
x.view(4, 2, 2, 4)

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],

         [[ 8,  9, 10, 11],
          [12, 13, 14, 15]]],


        [[[16, 17, 18, 19],
          [20, 21, 22, 23]],

         [[24, 25, 26, 27],
          [28, 29, 30, 31]]],


        [[[32, 33, 34, 35],
          [36, 37, 38, 39]],

         [[40, 41, 42, 43],
          [44, 45, 46, 47]]],


        [[[48, 49, 50, 51],
          [52, 53, 54, 55]],

         [[56, 57, 58, 59],
          [60, 61, 62, 63]]]])